<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-25J6UA9" ignored="0" name="Test" tests="10" failures="2" timestamp="24 Sep 2021 12:38:24 GMT" time="0.12" errors="0">
  <testcase name="tc0" time="0.024" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc0 -->
  <testcase name="tc0" time="0.0" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc0 -->
  <testcase name="tc0" time="0.004" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc0 -->
  <testcase name="tc0" time="0.004" classname="org.test.TestngRetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.test.TestngRetryLogic.tc0(TestngRetryLogic.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc0 -->
  <testcase name="tc1" time="0.0" classname="org.test.TestngRetryLogic"/>
  <testcase name="tc2" time="0.004" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="org.test.TestngRetryLogic">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.004" classname="org.test.TestngRetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.test.TestngRetryLogic.tc2(TestngRetryLogic.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.004" classname="org.test.TestngRetryLogic"/>
</testsuite> <!-- Test -->
